---
title: "CD2H NLP Sandbox: Exploring 2014 i2b2 De-id Challenge Data"
author: "Thomas Schaffter, thomas.schaffter@sagebionetworks.org"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: html_notebook
---

```{r}
rm(list=ls())

library(dplyr)
library(ggplot2)
library(purrr)
library(tibble)
library(tidyr)
library(xml2)
```

# Overview

This notebook provides some insights on the content of the data of the [2014 i2b2 de-identification challenge](https://portal.dbmi.hms.harvard.edu/projects/n2c2-2014/).

# Data

Here are the data that we use:

- Test Data: PHI Gold Set - Fixed (testing-PHI-Gold-fixed.tar.gz). Each XML file include the clinical note and the reference annotations.

```{r}
i2b2_gold_dir <- file.path("data", "testing-PHI-Gold-fixed")
```


```{r}
i2b2_gold_filenames <- fs::dir_ls(i2b2_gold_dir)

# Number of clinical notes in the evaluation dataset
length(i2b2_gold_filenames)
```


```{r}
# Get the nodes of TAGS from all the gold files as a data frame
annotations <- do.call("rbind", lapply(i2b2_gold_filenames, function(filename) {
  gold <- read_xml(filename)
  # Get the nodes of TAGS as a data frame
  xml_find_all(gold, "//TAGS/*") %>%
    purrr::map_dfr(~ {
      # Get the annotation type
      name <- xml_name(.x) %>% tibble::enframe() %>% tidyr::spread(name, value)
      colnames(name) <- c("name")
      # Get the property of the annotation
      attrs <- xml_attrs(.) %>% tibble::enframe() %>% tidyr::spread(name, value)
      # Get patient ID from filename
      patient_and_record_id <- strsplit(fs::path_ext_remove(fs::path_file(filename)), "-")[[1]]
      patient_id <- patient_and_record_id[1]
      record_id <- patient_and_record_id[2]
      
      cbind.data.frame(name, attrs, filename, patient_id, record_id) %>% set_tidy_names() %>% as_tibble() 
    }) %>%
    dplyr::rename(
      type = TYPE
    )
}))

head(annotations)
```


```{r}
# Number of annotations
nrow(annotations)
```


```{r}
# Identify how many clinical notes (count, %) inclue at least one instance of of a sensitive data type
annotations %>%
  group_by(name) %>%
  summarize(
    annos_count = length(filename),
    notes_count = length(unique(filename)), 
    notes_percent = round(100 * length(unique(filename)) / length(unique(annotations$filename)), digits = 2)
  ) %>%
  arrange(desc(annos_count))
```


```{r}
names <- annotations[annotations$name == 'NAME',]
table(names$type)
```


```{r}
names
```


```{r rows.print=30}
annotations %>%
  select(name, type, filename) %>%
  group_by(name, type) %>%
  summarize(
    annos_count = length(filename),
    notes_count = length(unique(filename)),
    notes_percent = round(100 * length(unique(filename)) / length(unique(annotations$filename)), digits = 2)
  ) %>%
  arrange(name, type, desc(annos_count))
```


```{r}
# Number of patients
length(unique(annotations$patient_id))
```


```{r}
# Number of record per patient
records_count_data <- annotations %>%
  select(patient_id, record_id) %>%
  group_by(patient_id) %>%
  summarize(
    records_count = length(unique(record_id))
  )

records_count_data
```


```{r}
# Barbplot number of patients with x records
ggplot(as.data.frame(table(records_count_data$records_count)), aes(Var1, Freq)) + 
  geom_bar(stat="identity", fill="steelblue") +
  xlab("Number of records") +
  ylab("Number of patients") +
  ggtitle("Number of patients with x records in the\ngold standard of 2014 i2b2 NLP De-id Challenge") +
  theme(plot.title = element_text(hjust = 0.5))
```


